### PR TITLE
Auth + delete recipe-lists

### PR DESCRIPTION
**Pull request by AlfredMadere**
1. Auth is added to backend but is only implemented in the GET /ingredients endpoint as of now to make it easy to continue development without everyone having to figure out the auth stuff to make progress. The front end will need to store the JWT token and send it in the headers of each request as you can see in the network tab on the /docs site. Checkout the docs site to see whats available, you can create an account and login via the auth/sign-up and auth/token endpoints

2. The delete /recipe-lists/{recipe-list-id} endpoint is implemented

### CODE REVIEW

**Review by michaelmurrayiv — APPROVED** [review]
Looks good! I like that you added a new separate file for the authentication (auth.py)!

**Comment by Abigayle-Mercer** [comment]
everyone was supposed to review this but someone accidentally pushed it - yikers

**Comment by AlfredMadere** [comment]
> Looks really good.
> 
> As far as authentication, it may be good in the future implement weak password policies in order to test user security. If time permits, it would also be beneficial to run Bandit to analyze our backends possible vulnerabilities.

Totally, we should spend a bunch of time making sure our backend is secure. For our wire frame demo and before we have any real user data I think there are other things we should focus on first. Definitely should be addressed at some point though. I've never heard of Bandit, what is that?

**Comment by AlfredMadere** [comment]
> Code is super easy to read, I would just be curious to know what the hash function is for the password.

It is an irreversible hashing function so that you can check if two things hash to the same value but not what the value actually is, its a security measure

**Comment by PauMinguet** [comment]
I know it was a bit hard to sync all of the auth while maintaining progress in all the other development (especially since auth initially breaks all functionality), but we are now on track to make everything work based on what user is logged in. Very good work Alfred.

**Comment by PauMinguet** [comment]
And I did merge accidentally instead of reviewing (sorry), so I'm glad that everyone reviewed it either before or after, approved of it, and canceled my Revert request. Good work team.

**Pull request merged**
